package com.pavan.employeemanagement.entity;

import jakarta.persistence.*;
import java.math.BigDecimal;

/** Represents a physical company asset held in inventory. */
@Entity
@Table(name = "assets", uniqueConstraints = @UniqueConstraint(columnNames = "serialNumber"))
public class Asset {
    // Primary key generated by MySQL.
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) private Long id;
    // Core inventory information.
    @Column(nullable = false) private String name;
    @Column(nullable = false) private String category;
    @Column(nullable = false) private String serialNumber;
    @Column(precision = 14, scale = 2) private BigDecimal value;
    @Enumerated(EnumType.STRING) private AssetStatus status = AssetStatus.AVAILABLE;
    public Long getId() { return id; }
    public String getName() { return name; } public void setName(String name) { this.name = name; }
    public String getCategory() { return category; } public void setCategory(String category) { this.category = category; }
    public String getSerialNumber() { return serialNumber; } public void setSerialNumber(String serialNumber) { this.serialNumber = serialNumber; }
    public BigDecimal getValue() { return value; } public void setValue(BigDecimal value) { this.value = value; }
    public AssetStatus getStatus() { return status; } public void setStatus(AssetStatus status) { this.status = status; }
}
