package com.pavan.employeemanagement.entity;

/** Defines the types of notifications generated by the system. */
public enum NotificationType {
    EMPLOYEE_CREATED, LEAVE_APPLIED, LEAVE_APPROVED, LEAVE_REJECTED,
    ASSET_ASSIGNED, ASSET_RETURNED,
    PROMOTION, BIRTHDAY,
    ATTENDANCE_ISSUE, PERFORMANCE_REVIEW,
    EMPLOYEE_UPDATED
}
